name: C build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    # Install dependencies
    - name: install deps
      run: sudo apt update && sudo apt -y install libliquid-dev libbtbb-dev libhackrf-dev libbladerf-dev libuhd-dev libfftw3-dev
    # Build
    - name: mkdir
      run: mkdir build
    - name: cmake build
      run: cmake -Bbuild -H.
    - name: cmake make
      run: cmake --build build/ --target all
